version: '3.8'

services:
  # Development environment
  robot_communication_dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: dev
    container_name: robot_communication_dev
    volumes:
      - ../src:/catkin_ws/src:rw
      - ../datasets:/catkin_ws/datasets:ro
      - ../scripts:/catkin_ws/scripts:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_HOSTNAME=localhost
    network_mode: "host"
    stdin_open: true
    tty: true
    command: bash

  # Robot data publisher service
  robot_publisher:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: prod
    container_name: robot_publisher
    volumes:
      - ../datasets:/catkin_ws/datasets:ro
      - ../config:/catkin_ws/config:ro
    environment:
      - ROS_MASTER_URI=http://roscore:11311
      - ROS_HOSTNAME=robot_publisher
    depends_on:
      - roscore
    networks:
      - ros_network
    command: roslaunch robot_communication robot_communication.launch

  # Mission server
  mission_server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: prod
    container_name: mission_server
    volumes:
      - ../config:/catkin_ws/config:ro
    environment:
      - ROS_MASTER_URI=http://roscore:11311
      - ROS_HOSTNAME=mission_server
    ports:
      - "8081:8080"  # TCP server port
    depends_on:
      - roscore
    networks:
      - ros_network
    command: rosrun robot_communication mission_server

  # ROS Master
  roscore:
    image: ros:noetic
    container_name: roscore
    environment:
      - ROS_MASTER_URI=http://roscore:11311
      - ROS_HOSTNAME=roscore
    networks:
      - ros_network
    command: roscore

  # Monitoring and visualization
  rqt:
    image: ros:noetic-desktop
    container_name: rqt
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_MASTER_URI=http://roscore:11311
      - ROS_HOSTNAME=rqt
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    networks:
      - ros_network
    depends_on:
      - roscore
    command: rqt
    profiles:
      - monitoring

  # RViz for visualization
  rviz:
    image: ros:noetic-desktop
    container_name: rviz
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_MASTER_URI=http://roscore:11311
      - ROS_HOSTNAME=rviz
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../config/rviz:/root/.rviz:rw
    networks:
      - ros_network
    depends_on:
      - roscore
    command: rviz
    profiles:
      - visualization

networks:
  ros_network:
    driver: bridge